# maintainer "Dima Ovcharenko <d.ovcharenko90@gmail.com>"

version: "3"
services:

  crserver-filter:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
    - 3333:80
    volumes:
    - ./conf.d/crserver-filter.conf:/etc/nginx/conf.d/crserver-filter.conf
    - ./data/nginx:/etc/nginx/lua
    - ./nginx/lualib:/usr/local/openresty/lualib/v8/
    - ./log:/usr/local/openresty/nginx/logs
    - /etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt
